version: "3"
services:
  vendor-portal:
    image: Maniraaj/dockerpractice
    environment:
    - BROWSER
    - HUB_HOST=hub    
    - THREAD_COUNT=1
    - TEST_SUITE=vendorApp.xml
    volumes:
    - C:/Users/manir/eclipse-workspace/dockerPractice/output/vendorApplication:/home/dockerpractice/test-output
  flight-reservation:
    image: Maniraaj/dockerpractice
    environment:
    - BROWSER
    - HUB_HOST=hub    
    - THREAD_COUNT=1   
    - TEST_SUITE=flight-reservation.xml
    volumes:
    - C:/Users/manir/eclipse-workspace/dockerPractice/output/flightApplication:/home/dockerpractice/test-output     