version: "3"
services:
  vendor-portal:
    image: Maniraaj/dockerpractice
    environment:
      - BROWSER=chrome
      - HUB_HOST=hub
      - THREAD_COUNT=3
      - TEST_SUITE=vendorApp.xml
    volumes:
      - C:/Users/manir/eclipse-workspace/dockerPractice/output/vendorApplication:/home/dockerpractice/test-output

  flight-reservation:
    image: Maniraaj/dockerpractice
    environment:
      - BROWSER=firefox
      - HUB_HOST=hub
      - THREAD_COUNT=3
      - TEST_SUITE=flightReserve.xml
    volumes:
      - C:/Users/manir/eclipse-workspace/dockerPractice/output/flightApplication:/home/dockerpractice/test-output
